[tox]
envlist = py311, lint, type, format
skip_missing_interpreters = true

[testenv]
deps = -r requirements-dev.txt
commands = python -m pytest tests backend/tests

[testenv:lint]
deps = flake8
commands = flake8 backend/src backend/tests

[testenv:type]
deps = mypy
commands = mypy backend/src --ignore-missing-imports

[testenv:format]
deps = black
commands = black --check backend/src backend/tests tools tests
