// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "TeslaAI",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(name: "TeslaAI", targets: ["TeslaAICore"])
    ],
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire.git", from: "5.6.4"),
        .package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", from: "1.6.0"),
        .package(url: "https://github.com/realm/realm-swift.git", from: "10.38.0"),
        .package(url: "https://github.com/kishikawakatsumi/KeychainAccess.git", from: "4.2.2"),
        .package(url: "https://github.com/Swinject/Swinject.git", from: "2.8.0"),
        .package(url: "https://github.com/airbnb/lottie-ios.git", from: "4.3.3"),
        .package(url: "https://github.com/mxcl/PromiseKit.git", from: "6.21.0"),
        .package(url: "https://github.com/grpc/grpc-swift.git", from: "1.19.0"),
        .package(url: "https://github.com/open-telemetry/opentelemetry-swift.git", from: "1.5.0"),
        .package(url: "https://github.com/firebase/firebase-ios-sdk.git", from: "10.23.0"),
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.26.0"),
        .package(url: "https://github.com/1024jp/GzipSwift.git", from: "6.0.0"),
        .package(url: "https://github.com/Boilertalk/Web3.swift.git", from: "0.6.0")
    ],
    targets: [
        .target(
            name: "TeslaAICore",
            dependencies: [
                "Alamofire",
                "CryptoSwift",
                .product(name: "RealmSwift", package: "realm-swift"),
                "KeychainAccess",
                "Swinject",
                "Lottie",
                "PromiseKit",
                .product(name: "GRPC", package: "grpc-swift"),
                .product(name: "OpenTelemetryApi", package: "opentelemetry-swift"),
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk"),
                .product(name: "FirebaseCrashlytics", package: "firebase-ios-sdk"),
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
                .product(name: "FirebaseMessaging", package: "firebase-ios-sdk"),
                "SwiftProtobuf",
                "GzipSwift",
                .product(name: "Web3", package: "Web3.swift")
            ]
        )
    ]
)
