#!/bin/bash
# path: platform-security/code-protection/intrusion_response/alert_to_guard.sh

# TeslaAI AI-GUARD Alert Forwarder v1.20
# Назначение: передача тревоги в модуль поведенческого анализа и реагирования AI Guard.
# Скрипт используется другими инструментами защиты (kill switch, honeyfiles, утечки и др.)

set -euo pipefail

# === Аргументы: тип инцидента, уровень, объект, источник ===
INCIDENT_TYPE=${1:-"unknown"}
SEVERITY=${2:-"medium"}
SOURCE_PATH=${3:-"unspecified"}
SOURCE_IP=${4:-"127.0.0.1"}

# === Метаданные ===
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
HOST_ID=$(hostname -f)
LOGFILE="/var/log/teslaai/alert_to_guard.log"
GUARD_ENDPOINT="http://localhost:8181/api/incident/ingest"

# === Формирование JSON ===
read -r -d '' PAYLOAD <<EOF
{
  "timestamp": "${TIMESTAMP}",
  "host": "${HOST_ID}",
  "severity": "${SEVERITY}",
  "incident_type": "${INCIDENT_TYPE}",
  "source_path": "${SOURCE_PATH}",
  "source_ip": "${SOURCE_IP}",
  "tags": ["autogenerated", "intrusion_detected", "guard_integration"]
}
EOF

# === Отправка запроса в Guard ===
curl -s -X POST -H "Content-Type: application/json" \
     -d "${PAYLOAD}" "${GUARD_ENDPOINT}" >> "${LOGFILE}" 2>&1

# === Логирование ===
echo "[${TIMESTAMP}] Alert sent to AI Guard: ${INCIDENT_TYPE} - ${SEVERITY} - ${SOURCE_PATH}" >> "${LOGFILE}"
