{
 "title": "RPC Overview",
 "tags": [
  "rpc",
  "observability",
  "sre",
  "red",
  "latency",
  "errors"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(rpc_server_duration_seconds_count, job)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(rpc_server_duration_seconds_count, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(rpc_server_duration_seconds_count, service)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(rpc_server_duration_seconds_count, instance)"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS (запросов/с)",
   "type": "stat",
   "description": "Суммарная скорость запросов RPC/HTTP/gRPC",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Успешность, %",
   "type": "stat",
   "description": "Доля успешных ответов",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(rpc_server_duration_seconds_count{status_code=~\"OK|UNSET|2..|3..\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(rate(rpc_server_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    },
    {
     "expr": "100 * sum(rate(http_server_request_duration_seconds_count{status_code=~\"2..|3..\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    },
    {
     "expr": "100 * sum(rate(grpc_server_handled_total{grpc_code=\"OK\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(rate(grpc_server_handled_total{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Ошибки, %",
   "type": "stat",
   "description": "Доля ошибочных ответов",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(rpc_server_duration_seconds_count{status_code!~\"OK|UNSET|2..|3..\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(rate(rpc_server_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    },
    {
     "expr": "100 * sum(rate(http_server_request_duration_seconds_count{status_code!~\"2..|3..\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    },
    {
     "expr": "100 * sum(rate(grpc_server_handled_total{grpc_code!=\"OK\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) / sum(rate(grpc_server_handled_total{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "P95 латентность, s",
   "type": "stat",
   "description": "Текущая P95 по длительности обработки",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(rpc_server_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_request_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])))"
    }
   ]
  },
  { "title": "Латентность", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Латентность P50/P95/P99 (s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "legendFormat": "P50",
     "expr": "histogram_quantile(0.50, sum by (le) (rate(rpc_server_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) + sum by (le) (rate(http_server_request_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) + sum by (le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])))"
    },
    {
     "legendFormat": "P95",
     "expr": "histogram_quantile(0.95, sum by (le) (rate(rpc_server_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) + sum by (le) (rate(http_server_request_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) + sum by (le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])))"
    },
    {
     "legendFormat": "P99",
     "expr": "histogram_quantile(0.99, sum by (le) (rate(rpc_server_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) + sum by (le) (rate(http_server_request_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])) + sum by (le) (rate(grpc_server_handling_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\", instance=~\"$instance\"}[$__rate_interval])))"
    }
   ]
  },
  { "title": "Ошибки", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Ошибка, % (во времени)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "legendFormat": "RPC",
     "expr": "100 * sum(rate(rpc_server_duration_seconds_count{status_code!~\"OK|UNSET|2..|3..\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])) / sum(rate(rpc_server_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))"
    },
    {
     "legendFormat": "HTTP",
     "expr": "100 * sum(rate(http_server_request_duration_seconds_count{status_code!~\"2..|3..\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))"
    },
    {
     "legendFormat": "gRPC",
     "expr": "100 * sum(rate(grpc_server_handled_total{grpc_code!=\"OK\", job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval])) / sum(rate(grpc_server_handled_total{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Коды ответов (последние 5 минут)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "legendFormat": "{{status_code}}",
     "expr": "sum by (status_code) (rate(rpc_server_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[5m]))"
    },
    {
     "legendFormat": "{{status_code}}",
     "expr": "sum by (status_code) (rate(http_server_request_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[5m]))"
    },
    {
     "legendFormat": "{{grpc_code}}",
     "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{job=~\"$job\", namespace=~\"$namespace\", service=~\"$service\"}[5m]))"
    }
   ]
  }
 ]
}