{
 "title": "PVC Usage Overview",
 "tags": [
  "kubernetes",
  "storage",
  "pvc",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kubelet_volume_stats_capacity_bytes, namespace)"
   },
   {
    "name": "pvc",
    "query": "label_values(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}, persistentvolumeclaim)"
   },
   { "name": "topn", "query": "5,10,20" }
  ]
 },
 "panels": [
  {
   "title": "Cluster PVC usage (%)",
   "type": "stat",
   "description": "Суммарный процент использования PVC по выбранным namespace/PVC",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"})"
    }
   ]
  },
  {
   "title": "Total PVC used (GiB)",
   "type": "timeseries",
   "description": "Суммарно использовано по выбранным namespace/PVC",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) / 1024 / 1024 / 1024",
     "legendFormat": "used GiB"
    }
   ]
  },
  {
   "title": "Top-$topn PVC by % used",
   "type": "bargauge",
   "description": "Наиболее заполненные PVC (instant, topk)",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($topn, 100 * kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"})",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC usage table",
   "type": "table",
   "description": "Таблица: namespace, pvc, storageclass, used/capacity/available, % used",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 16 },
   "targets": [
    {
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}",
     "expr": "(100 * kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) * on(namespace,persistentvolumeclaim) group_left(storageclass) kube_persistentvolumeclaim_info{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}"
    },
    {
     "legendFormat": "used GiB",
     "expr": "(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} / 1024 / 1024 / 1024) * on(namespace,persistentvolumeclaim) group_left(storageclass) kube_persistentvolumeclaim_info{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}"
    },
    {
     "legendFormat": "capacity GiB",
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} / 1024 / 1024 / 1024) * on(namespace,persistentvolumeclaim) group_left(storageclass) kube_persistentvolumeclaim_info{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}"
    },
    {
     "legendFormat": "available GiB",
     "expr": "(kubelet_volume_stats_available_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} / 1024 / 1024 / 1024) * on(namespace,persistentvolumeclaim) group_left(storageclass) kube_persistentvolumeclaim_info{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}"
    }
   ]
  }
 ]
}